aliases:
  CL: tCL
  CAS: tCL
  CAS Latency: tCL
  tRCD Read: tRCDRD
  tRCD Write: tRCDWR
  tRFC1: tRFC
  tREFIx9: tREFI
  Command Rate: command_rate
  CR: command_rate
  tWTR_S: tWTRS
  tWTR_L: tWTRL
  tRRD_S: tRRDS
  tRRD_L: tRRDL
  tWRPRE: tWRPRE
  tRDPRE: tRDPRE
